#!/usr/bin/env python3
"""
Build step for the Java 9->26 reference (no runtime deps, stdlib only).

Generates:
  assets/search-index.js   window.SEARCH_INDEX = [...]  (offline content search)
  print.html               every page's <main> concatenated, print-friendly

Re-run after editing any page:  python3 build.py
"""
import re, os, json, html, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
os.chdir(ROOT)

# Pages to index / print, in reading order.
PAGES = [
    "index.html", "quickstart.html", "features.html",
    "versions/java-8.html",
    "versions/java-9.html", "versions/java-11.html", "versions/java-17.html",
    "versions/java-21.html", "versions/java-25.html", "versions/java-26.html",
    "topics/generics.html", "topics/reflection.html", "topics/annotations.html",
    "topics/var.html", "topics/records.html", "topics/sealed-classes.html",
    "topics/pattern-matching-switch.html", "topics/text-blocks-strings.html",
    "topics/modules-jpms.html", "topics/stream-api.html", "topics/virtual-threads.html",
    "topics/structured-concurrency.html", "topics/scoped-values.html",
    "topics/streams-gatherers.html", "topics/ffm-api.html", "topics/jvm-memory-gc.html",
]

PAGE_SET = set(PAGES)

def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()

def strip_tags(s):
    s = re.sub(r"<[^>]+>", " ", s)
    return re.sub(r"\s+", " ", html.unescape(s)).strip()

def get_main(doc):
    m = re.search(r"<main\b[^>]*>(.*?)</main>", doc, re.S | re.I)
    return m.group(1) if m else ""

def get_title(doc):
    m = re.search(r"<title>(.*?)</title>", doc, re.S | re.I)
    return html.unescape(m.group(1).strip()) if m else ""

# ---------------------------------------------------------------- search index
def build_index():
    entries = []
    for page in PAGES:
        doc = read(page)
        main = get_main(doc)
        title = get_title(doc)
        h1 = re.search(r"<h1[^>]*>(.*?)</h1>", main, re.S | re.I)
        h1 = strip_tags(h1.group(1)) if h1 else title
        # section headings become jump targets (only those with id would anchor,
        # but we link to the page; headings improve match quality)
        heads = [strip_tags(h) for h in
                 re.findall(r"<h[23][^>]*>(.*?)</h[23]>", main, re.S | re.I)]
        # code identifiers help searches like "readString"
        code = " ".join(strip_tags(c) for c in
                        re.findall(r"<code[^>]*>(.*?)</code>", main, re.S | re.I))
        body = strip_tags(main)
        entries.append({
            "url": page,
            "title": h1,
            "headings": heads,
            # keep the index small: a text snippet + code tokens
            "text": (body[:1200] + " " + code)[:2000],
        })
    js = "window.SEARCH_INDEX = " + json.dumps(entries, ensure_ascii=False) + ";\n"
    with open("assets/search-index.js", "w", encoding="utf-8") as f:
        f.write(js)
    kb = round(len(js.encode("utf-8")) / 1024, 1)
    print(f"  assets/search-index.js  ({len(entries)} pages, {kb} KB)")

# ---------------------------------------------------------------- print bundle
PRINT_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Java Evolution — complete reference (print / all-in-one)</title>
<link rel="stylesheet" href="assets/style.css">
<style>
  /* single-column, print-optimised */
  body { background:#fff; }
  .print-wrap { max-width: 950px; margin: 0 auto; padding: 24px; }
  .print-page { page-break-after: always; border-bottom: 2px solid var(--border);
                padding-bottom: 32px; margin-bottom: 32px; }
  .print-page:last-child { page-break-after: auto; border-bottom: none; }
  .print-toc a { display:block; padding:2px 0; }
  .ba { grid-template-columns: 1fr 1fr; }
  .toolbar { position: sticky; top:0; background:#fff; padding:10px 0;
             border-bottom:1px solid var(--border); margin-bottom:16px; }
  @media print {
    .toolbar { display:none; }
    a { color: inherit; text-decoration: none; }
    pre { white-space: pre-wrap; word-break: break-word; }
  }
</style>
</head>
<body data-theme="light">
<div class="print-wrap">
<div class="toolbar">
  <strong>Java Evolution — all-in-one</strong> &nbsp;
  <button onclick="window.print()" class="theme-toggle">⎙ Print / Save as PDF</button> &nbsp;
  <a href="index.html">← back to the interactive site</a>
</div>
<h1 id="top">Java Evolution — Complete Reference</h1>
<p class="lead">Every page concatenated for printing or PDF export. Generated by <code>build.py</code>.</p>
"""

PRINT_FOOT = """
</div>
<script src="assets/highlight.js"></script>
</body>
</html>
"""

def _anchor_for(path):
    return "pg-" + re.sub(r"[^a-z0-9]+", "-", path.lower())

def fix_links(main_html, page_dir):
    """Rewrite internal .html links into in-document anchors so the single-file
    print bundle is self-navigating. Links resolve relative to the page's own
    directory, then map to the #pg-... section anchor of the target page."""
    def repl(m):
        pre, href, frag, post = m.group(1), m.group(2), m.group(3) or "", m.group(4)
        target = os.path.normpath(os.path.join(page_dir, href)).replace(os.sep, "/")
        if target == "index.html":
            return f'{pre}#top{post}'          # index has no section; jump to top
        if target in PAGE_SET:
            return f'{pre}#{_anchor_for(target)}{post}'
        return m.group(0)                        # leave external / unknown links
    # matches href="....html"  or href="....html#frag"
    return re.sub(r'(href=")([^":]+?\.html)(#[^"]*)?(")', repl, main_html)

def build_print():
    parts = [PRINT_HEAD]
    # table of contents
    toc = ['<div class="print-toc"><h2>Contents</h2>']
    for page in PAGES:
        if page == "index.html":
            continue
        title = get_title(read(page))
        anchor = "pg-" + re.sub(r"[^a-z0-9]+", "-", page.lower())
        toc.append(f'<a href="#{anchor}">{html.escape(title)}</a>')
    toc.append("</div>")
    parts.append("\n".join(toc))

    for page in PAGES:
        if page == "index.html":
            continue
        doc = read(page)
        main = fix_links(get_main(doc), os.path.dirname(page))
        # drop the interactive-only feature filter input on features.html
        main = re.sub(r'<input id="feat-filter"[^>]*>', "", main)
        anchor = "pg-" + re.sub(r"[^a-z0-9]+", "-", page.lower())
        parts.append(f'<section id="{anchor}" class="print-page">{main}</section>')
    parts.append(PRINT_FOOT)
    with open("print.html", "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    kb = round(os.path.getsize("print.html") / 1024, 1)
    print(f"  print.html  ({kb} KB)")

if __name__ == "__main__":
    print("Building:")
    build_index()
    build_print()
    print("Done.")
